### ISSUE TITLE
Version 0.9.4

### ISSUE THREAD

**Issue by KateM6** [inexorabletash/PcxFileType#1]
Hello Joshua,

would you be so kind an provide a download version of pcx file support dll (0.9.4.0) with support for paint.net 4.0.
At http://www.calormen.com/tmp/PcxFileType.zip there is only version 0.9.3.0

Thanks in advance
Rainer

**Comment by inexorabletash** [comment]
Hrm, I probably just forgot to bump the assembly info. The version on calormen.com has the latest code (readme says 9.4.0)

I'll rebuild when I have a chance. Thanks for the poke!

**Comment by KateM6** [comment]
Thank you very much. Anyway, should this Version work with pain.net 4.0.5?
I still receive an error message:

System.MissingMethodException: Method not found: 'Int32 PaintDotNet.Utility.ReadUInt16(System.IO.Stream)'.
   at PcxFileTypePlugin.PcxFileType.PcxHeader.ReadUInt16(Stream input)
   at PcxFileTypePlugin.PcxFileType.PcxHeader..ctor(Stream input)
   at PcxFileTypePlugin.PcxFileType.OnLoad(Stream input)
   at PaintDotNet.FileType.Load(Stream input) in d:\src\pdn\paintdotnet\src\Data\FileType.cs:line 477
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in d:\src\pdn\paintdotnet\src\Base\Functional\Func.cs:line 158

**Comment by inexorabletash** [comment]
My apologies. I must not have updated the DLL in the zip correctly last time. :(

I've rebuilt, confirm it works with PDN 4.0.5, and updated the ZIP:

http://www.calormen.com/tmp/PcxFileType.zip 

Please give it another try, and confirm that it works for you?

**Comment by KateM6** [comment]
GREAT!
Thank you very much for your support, I appreciate your fast feedback.
